---
title: "LUV QC Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)
#library(htmlwidgets)
library(leaflet)
#library(sp)
library(rgdal)
library(dplyr)


# environment inputs
attribute <- c("population", "households","employment", "residential_units")
geography <- c( "zone", "faz", "city")
year1 <- (2040)
year2 <- (2040)
extension <- ".csv"

trim <- function (x) gsub("^\\s+|\\s+$", "", x) # function for triming whitespace 

make <- nchar(Sys.getenv('QC_NAME')) > 0 

if(make) {
  base.dir <- Sys.getenv('QC_BASE_DIRECTORY')
  run1 <- Sys.getenv('QC_RUN1')
  run2.all <- Sys.getenv('QC_RUN2')
  run2.all <- trim(unlist(strsplit(run2.all, ","))) # run2 can have multiple directories; split by comma
  #result.dir <- Sys.getenv('QC_RESULT_PATH')
  wrkdir <- file.path(Sys.getenv('QC_SCRIPT_PATH'), "..")
  dsn <- file.path(wrkdir, "data")
} else {
  base.dir <- "//modelsrv3/e$/opusgit/urbansim_data/data/psrc_parcel/runs"
  #base.dir <- "/Volumes/e$/opusgit/urbansim_data/data/psrc_parcel/runs"
  run1 <- "run_74.run_2016_06_16_15_40"
  run2.all <- c("run_73.run_2016_06_13_16_56","luv_1.compiled")
  run.name <- 'run74'
  dsn <- "C:/Users/Christy/Desktop/luv/QC/data"
  #dsn <- "/Users/hana/ForecastProducts/LUV/QC/data"
  #result.dir <- file.path("C:/Users/Christy/Desktop/luv/QC/results", run.name)
}

faz.lookup <- read.table(file.path(dsn, "faz_names.txt"), header =TRUE, sep = "\t")
zone.lookup <- read.table(file.path(dsn, "zones.txt"), header =TRUE, sep = "\t")
city.lookup <- read.table(file.path(dsn, "cities.csv"), header =TRUE, sep = ",")

layer_faz <- "FAZ_2010_WGS84"
layer_zone <- "TAZ_2010_WGS84"
layer_city <- "JURIS_2014_WGS84"
  
runname1 <- unlist(strsplit(run1,"[.]"))[[1]]
runnames2 <- sapply(strsplit(run2.all,"[.]"), function(x) x[1]) # can have multiple values

for (irun in 1:length(run2.all)) {
	run2 <- run2.all[irun]
	runname2 <- runnames2[irun]

	# build plotly source table
	for (a in 1:length(geography)){
	  
	  indicators.table <- NULL
	  
	  for (i in 1:length(attribute)){
	    # run1
	    filename1 <- paste0(geography[a],'__',"table",'__',attribute[i], extension)
	    datatable1 <- read.csv(file.path(base.dir, run1,"indicators",filename1), header = TRUE, sep = ",")
	    column_id <- colnames(datatable1)[grepl("_id",names(datatable1))]
	    column_est <-colnames(datatable1)[grepl(year1,names(datatable1))]
	    table1 <- datatable1[,c(column_id,column_est)]
	    colnames(table1)[2] <- paste0("estrun1")
	    
	    # run2
	    filename2 <- paste0(geography[a],'__',"table",'__',attribute[i], extension)
	    datatable2 <- read.csv(file.path(base.dir, run2,"indicators",filename2), header = TRUE, sep = ",")
	    column_id2 <- colnames(datatable2)[grepl("_id",names(datatable2))]
	    column_est2 <-colnames(datatable2)[grepl(year2,names(datatable2))]
	    table2 <- datatable2[,c(column_id2,column_est2)]
	    colnames(table2)[2] <- paste0("estrun2")
	    
	    # merge tables
	    merge.table <- merge(table1, table2, by = colnames(datatable2)[grepl("_id",names(datatable2))])
	    if (geography[a]=="zone"){
	      merge.table <- merge(merge.table, zone.lookup, "zone_id") %>% merge(faz.lookup, "faz_id") 
        merge.table$diff <- merge.table$estrun1-merge.table$estrun2
        merge.table <- merge.table[,c(2, 1, 3, 4, 8, 7)] 
	    } else if (geography[a]=="faz"){
	        merge.table <- merge(merge.table, faz.lookup, "faz_id")
          merge.table$diff <- merge.table$estrun1-merge.table$estrun2
          merge.table <- merge.table[,c(1:3, 5, 4)] 
	    } else {
	        merge.table <- merge(merge.table, city.lookup, "city_id")
	        merge.table$diff <- merge.table$estrun1-merge.table$estrun2
	    }
	     
	    merge.table$indicator <- switch(attribute[i],
	                                    "population"="Total Population", 
	                                    "households"="Households", 
	                                    "employment"="Employment", 
	                                    "residential_units"="Residential Units")
	    ifelse (is.null(indicators.table),
	            indicators.table <- merge.table, 
	            indicators.table <- rbind(indicators.table, merge.table))
	    
	  } # end of attribute loop
	  
    # assign tables and shapefiles to geography-based list
    if (geography[a]=="faz"){
      faz.shape <- readOGR(dsn=dsn,layer=layer_faz) %>% sp::merge(faz.lookup, by.x = "FAZ10", by.y = "faz_id")
      faz.shape$name_id <- faz.shape$FAZ10
      faz <- list(tbl = indicators.table, shp = faz.shape)
    } else if (geography[a]=="zone"){
      zone.shape <- readOGR(dsn=dsn,layer=layer_zone) %>% sp::merge(zone.lookup, by.x = "TAZ", by.y = "zone_id")
      zone.shape$name_id <- zone.shape$TAZ
      zone <- list(tbl = indicators.table, shp = zone.shape)
    } else {
      city.shape <- readOGR(dsn=dsn,layer=layer_city) %>% sp::merge(city.lookup, by = "city_id")
      city.shape$name_id <- city.shape$city_id
      city.shape$Name <- city.shape$city_name
      city <- list(tbl = indicators.table, shp = city.shape)
    }
	  
	} # end of geography loop
	
	# assign geography, tables, and shapefiles to run2 lists
	assign(paste(runname2, ".data", sep=""), list(zone = zone, faz = faz, city = city))
	
} # end run2 loop	
```

Run Comparison
=======================================================================
Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(inputId = "select_run2",
            label = h4(paste0("Compare ",`runname1`," with")),
            choices = runnames2
            )
```

####And select the following:
```{r}

selectInput(inputId = "select_geography",
            label = h5("Geography"),
            choices = c("TAZ" = 1,
                        "FAZ" = 2,
                        "City" = 3),
            selected = 1)

selectInput(inputId = "select_indicator",
            label = h5("Indicator"),
            choices = c("Total Population"= 1,
                        "Households"= 2,
                        "Employment"= 3,
                        "Residential Units"= 4),
            selected = 1)

```

Use the 'Box Select' or 'Lasso Select' option in the scatterplot to select points and view its location on the map.

Column
-----------------------------------------------------------------------

### Scatterplot

```{r}
# global reactions
run <- reactive({
  paste0(input$select_run2, ".data")
})

table <- reactive({ 
        switch(as.integer(input$select_indicator),
              "Total Population",
              "Households",
              "Employment",
              "Residential Units") 
})

geog <- reactive({
        geo <- as.integer(input$select_geography)
        get(run())[[geo]][[1]]
})

# Plotly
output$plot <- renderPlotly({
 
  data <- subset(geog(), geog()$indicator==table()) 
  runname2.trim <- sapply(strsplit(run(),"[.]"), function(x) x[1])
  
  # uniquely identify geo for Plotly
  switch(as.integer(input$select_geography),
         key <- data$zone_id,
         key <- data$faz_id,
         key <- data$city_id)
  
  p <- plot_ly(data,
               x = estrun1,
               y = estrun2,
               name = "",
               source = "source",
               text = paste0("ID: ", data[,1], 
                             " Name: ", data[,grepl("name|Name|city_name",names(data))]),
               type = 'scatter',
               key = key, # will appear in 'eventdata'
               mode = 'markers',
               showlegend = F)%>%
      add_trace(x=c(0,max(estrun1)), 
                y=c(0,max(estrun1)),
                marker = list(color="grey", size = 0),
                opacity = .6,
                mode = "lines",
                showlegend = F)%>%
      layout(font = list(family="Segoe UI", size = 13.5),
             title = " ",
             xaxis = list(title = runname1),
             yaxis = list(title = runname2.trim),
             margin = list(l=100, b=100, t=90, r=100)
             )
  p
})

plotlyOutput('plot', width = "80%", height = "925px")

```

Column
-----------------------------------------------------------------------

### Map

```{r}
# global reactions
# Shapefile
shape_select <- reactive({ 
                geo <- as.integer(input$select_geography)
                get(run())[[geo]][[2]]
})

shape <- reactive({
  data1 <- subset(geog(), geog()$indicator==table())
  if (input$select_geography == 1){
    shape.join <- sp::merge(shape_select(), data1, by.x = c("TAZ"), by.y = c("zone_id"))
    return(shape.join)
  } else if (input$select_geography == 2){
    shape.join <- sp::merge(shape_select(), data1, by.x = c("FAZ10", "Name"), by.y = c("faz_id", "Name"))
    return(shape.join)
  } else {
    shape.join <- sp::merge(shape_select(), data1, by = "city_id")
    return(shape.join)
  }
})

# leaflet layer control
geo <- reactive({
  if (input$select_geography == 1){
    geo <- "TAZ"
    return(geo)
  } else if (input$select_geography == 2){
    geo <- "FAZ"
    return(geo)
  } else {
    geo <- "City"
    return(geo)
  }
})

# Draw the map without selected geographies
output$map <- renderLeaflet({
  
  runname2.trim <- sapply(strsplit(run(),"[.]"), function(x) x[1])
  
  # Set up symbology and categorization
    rng <- range(shape()$diff)
    if (rng[1] < 0 & rng[2] > 0){
      diff.range <- "both"
    } else if (rng[1] >=0 & rng[2] > 0){
      diff.range <- "pos"
    } else if (rng[1] < 0 & rng[2] < 0){
      diff.range <- "neg"
    } else {
      diff.range <- "none"
    }

    if (diff.range == "both"){
      color <- c("#053061",
                 "#2166ac", 
                 "#4393c3", 
                 "#92c5de", 
                 "#d1e5f0", 
                 "#ffffff", 
                 "#f7f7f7", 
                 "#fddbc7", 
                 "#f4a582", 
                 "#d6604d", 
                 "#b2182b", 
                 "#67001f")
      if (input$select_geography == 1){ # separate bins for TAZ
      bin <- c(-70000, -3000, -1000, -500,- 250, 0, 1, 250, 500, 1000, 3000, 70000)
      } else { # for other geographies
      bin <- c(-70000, -30000, -10000, -5000,- 2500, 0, 1, 2500, 5000, 10000, 30000, 70000)
      }
    } else if (diff.range == "pos"){
      color <- "Reds"
      bin <- c(0, 500, 1000, 2500, 5000, 7000, 10000, 25000, 30000, 70000)
    } else if (diff.range == "neg"){
      color <- "Blues"
      bin <- c(-70000, -30000, -10000, -25000, -5000,- 2500, -1000, -500, 0)
    } else if (diff.range == "none"){
      color <- "transparent"
      bin <- c(0, 1)
    }
    
    pal <- colorBin(palette = color, bins = bin, domain=shape()$diff, pretty = FALSE)    

    geo.popup1 <- paste0("<strong>ID: </strong>", shape()$name_id,
                          "<br><strong>Large Area Name: </strong>", shape()$Name,
                          "<br><strong>", runname1," estimate: </strong>", shape()$estrun1,
                          "<br><strong>", runname2.trim," estimate: </strong>", shape()$estrun2,
                          "<br><strong>Difference: </strong>", shape()$diff
                         )
                         
    map <- leaflet()%>%
            addProviderTiles("CartoDB.Positron", group = "Street Map")%>%
            addProviderTiles("Esri.WorldImagery", group = "Imagery")%>%
            clearShapes()%>%
            addPolygons(data = shape(),
                        fillColor = ~pal(shape()$diff),
                        fillOpacity = 0.7,
                        stroke = TRUE,
                        color = "#8a8a95",
                        weight = 1,
                        group = geo(),
                        popup = geo.popup1
                        )%>%
            addLegend(position = "bottomright",
                      pal = pal,
                      values = pal(shape()$diff),
                      title = paste0("Run difference by ", geo()),
                      opacity =1,
                      labFormat = labelFormat(digits = 0, big.mark = ","))

    # Re-draw the map with selected geographies    
    subdata <- selected_geo()
    if(length(subdata) > 0)
        map <- map %>% 
                addPolygons(data = selected_geo(),
                            fill = FALSE,
                            color = '#FFFF00',
                            opacity = 1,
                            group = paste0("Selected ", geo()))

    map <- map %>%
       setView(lng = -122.008546, lat = 47.549390, zoom = 9)%>%
       addLayersControl(baseGroups = c("Street Map", "Imagery"),
                        overlayGroups = c(geo(), paste0("Selected ", geo())),
                        options = layersControlOptions(collapsed = FALSE))
    map  
    
})


# Drag event for the scatterplot: will grab ids of selected points
selected_geo <- reactive({
  eventdata <- event_data(event = "plotly_selected", source = "source")
  if(is.null(eventdata)){
    return(NULL) # do nothing
  } else {
    geoid <- eventdata[['key']]
    if (input$select_geography == 1){
      sub <- shape()[shape()$TAZ %in% geoid, ] # Give back a sp data frame of the selected ids
      return(sub)
    } else if (input$select_geography == 2){
      sub <- shape()[shape()$nFAZ10 %in% geoid, ] 
      return(sub)
    } else {
      sub <- shape()[shape()$city_id %in% geoid, ] 
      return(sub)
    } 
  }
}) 


leafletOutput("map")


```

Tab 2
=======================================================================

Tab 3
=======================================================================
